apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-environment
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cicd
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: environments/local
    repoURL: https://github.com/robotjoosen/cluster-management-template
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
