apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: monitoring
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.50.8
    helm:
      releaseName: grafana
      values: |
        ingress:
            enabled: true
            hosts:
              - grafana.monitoring.localhost
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Prometheus (Management)
              type: prometheus
              url: http://prometheus-kube-prometheus-prometheus.prometheus:9090
              access: proxy
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
