apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: devtools
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 21.1.0
    helm:
      values: |
        ingressRoute:
          dashboard:
            entryPoints:
              - web
            enabled: true
            matchRule: Host(`traefik.localhost`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
        ingressClass:
          enabled: true
          isDefaultClass: true
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
